#include <bits/stdc++.h>

/**
 * problem D (4/6)
 * codeforces, codeforces-round-1067-div2
 * author: @shamir0xe
 * generated by contest-builder
 * https://github.com/shamir0xe/contest-builder
 **/

typedef long long ll;
typedef std::pair<int, int> pii;
typedef std::vector<int> vi;
typedef std::vector<long long> vl;
typedef std::vector<std::vector<int>> vvi;
typedef std::vector<std::vector<ll>> vvl;
#define range(i, n) for (int i = 0; i < n; ++i)
#define rrange(i, n) for (int i = n - 1; i >= 0; --i)
#define fr(i, a, n) for (int i = a; i < n; ++i)
#define rfr(i, a, n) for (int i = n - 1; i >= a; --i)
#define trace(x) std::cerr << #x << " : " << x << std::endl
#define _ << " " <<
#define sz(x) ((int)(x).size())
#define all(x) (x).begin(), (x).end()
#define X first
#define Y second

/**
 * printing tuples
 **/
template <size_t n, typename... T>
typename std::enable_if<(n >= sizeof...(T))>::type
__tuple_printer(std::ostream &os, const std::tuple<T...> &tup) {};

template <size_t n, typename... T>
typename std::enable_if<(n < sizeof...(T))>::type
__tuple_printer(std::ostream &os, const std::tuple<T...> &tup) {
  if (n != 0) {
    os << " ";
  }
  os << std::get<n>(tup);
  __tuple_printer<n + 1>(os, tup);
};

template <typename... T>
std::ostream &operator<<(std::ostream &os, const std::tuple<T...> &tup) {
  os << "(";
  __tuple_printer<0>(os, tup);
  os << ")";
  return os;
}

/**
 * printing pairs
 **/
template <typename T, typename K>
std::ostream &operator<<(std::ostream &os, const std::pair<T, K> &p) {
  os << "(" << p.first << " " << p.second << ")";
  return os;
}

/**
 * printing vectors
 **/
template <class T>
std::ostream &operator<<(std::ostream &os, const std::vector<T> &v) {
  os << "[";
  bool first = true;
  for (auto ii = v.begin(); ii != v.end(); ++ii) {
    if (first) {
      first = false;
    } else {
      os << " ";
    }
    os << (*ii);
  }
  os << "]";
  return os;
}

template <typename T, typename K = std::function<void(void)>>
void smin(T &a, T b, const K callable = []() {}) {
  if (a > b) {
    a = b;
    callable();
  }
}

template <typename T, typename K = std::function<void(void)>>
void smax(T &a, T b, const K callable = []() {}) {
  if (a < b) {
    a = b;
    callable();
  }
}

/**
 * Reader class
 **/
class Reader {
public:
  template <typename T> inline static T primitive() {
    T temp;
    std::cin >> temp;
    return temp;
  }

  template <typename T> static std::vector<T> vector(int n) {
    std::vector<T> res(n);
    range(i, n) { res[i] = Reader::primitive<T>(); }
    return res;
  }

  template <typename T, size_t n> static std::array<T, n> array() {
    std::array<T, n> res;
    range(i, n) { res[i] = Reader::primitive<T>(); }
    return res;
  }

  static void sync() {
    std::ios_base::sync_with_stdio(false);
    std::cin.tie(nullptr);
  }
};

/**
 * define variables here
 **/
const int maxn = 1000 * 100 + 5;

/**
 * define functions here
 **/
int n;

auto find_moves(std::string s, std::vector<pii> &moves) {
  std::string curr = s;
  int i = 0;
  while (i < n) {
    int j = i + 1;
    while (j < n && curr[i] == curr[j]) {
      j++;
    }
    j--;
    if (j - i + 1 == n) {
      break;
    }
    if (j - i + 1 > 1) {
      moves.push_back({i, j});
      for (int t = i; t <= j; t++) {
        curr[t] = (curr[t] == '0' ? '1' : '0');
      }
      i = 0;
      continue;
    }
    i++;
  }
  int zeros = 0;
  range(i, n) {
    if (curr[i] == '0') {
      zeros++;
    }
  }
  if (zeros == n) {
    return curr;
  }
  if (zeros == 0 && n > 1) {
    moves.push_back({0, n - 1});
    for (int t = 0; t < n; t++) {
      curr[t] = (curr[t] == '0' ? '1' : '0');
    }
    return curr;
  }
  if (n > 3) {
    if (curr[0] == curr[n - 1]) {
      moves.push_back({0, n - 3});
      for (int t = 0; t <= n - 3; t++) {
        curr[t] = (curr[t] == '0' ? '1' : '0');
      }
      return find_moves(curr, moves);
    } else {
      moves.push_back({0, n - 2});
      for (int t = 0; t <= n - 2; t++) {
        curr[t] = (curr[t] == '0' ? '1' : '0');
      }
      return find_moves(curr, moves);
    }
  }
  return curr;
};

auto solve() {
  /**
   * main logic goes here
   **/
  std::string s, t;
  std::cin >> n >> s >> t;
  if (s == t) {
    std::cout << 0 << std::endl;
    return 0;
  }

  std::vector<pii> moves_1, moves_2;
  auto o1 = find_moves(s, moves_1);
  auto o2 = find_moves(t, moves_2);
  if (o1 != o2) {
    std::cout << -1 << std::endl;
    return 0;
  }
  std::cout << sz(moves_1) + sz(moves_2) << std::endl;
  for (pii move : moves_1) {
    std::cout << move.X + 1 << " " << move.Y + 1 << std::endl;
  }
  std::reverse(all(moves_2));
  for (pii move : moves_2) {
    std::cout << move.X + 1 << " " << move.Y + 1 << std::endl;
  }
  return 0;
}

int second_main() {
  auto ans = solve();
  // range(i, n) { std::cout << ans[i] << " \n"[i == sz(ans) - 1]; }
  // std::cout << ans << std::endl;
  return 0;
}

int main() {
  Reader::sync();
  bool test_case = true;
  if (test_case) {
    int t;
    std::cin >> t;
    while (t--) {
      second_main();
    }
  } else {
    second_main();
  }
  return 0;
}
