package main

import (
	"fmt"
)

/**
 * problem B (2/4)
 * leetcode, biweekly-contest-168
 * author: @shamir0xe
 * generated by contest-builder
 * https://github.com/shamir0xe/contest-builder
 **/

func maxSumOfSquares(num int, sum int) string {
	if sum > num*9 {
		return ""
	}
	var t int = sum / num
	var res []byte = make([]byte, num)
	for i := range num {
		res[i] = byte('0')
	}
	t = sum / 9
	for i := range t {
		res[i] = byte('9')
	}
	r := sum - t*9
	if r > 0 {
		if t < num {
			res[t] = byte('0' + r)
		} else {
			return ""
		}
	}
	return string(res)
}

func main() {
	fmt.Println("Hello world!")
}
