package main

import "fmt"

/**
 * problem B (2/4)
 * leetcode, weekly-contest-472
 * author: @shamir0xe
 * generated by contest-builder
 * https://github.com/shamir0xe/contest-builder
 **/

func longestBalanced(nums []int) int {
	var ans int = -1
	n := len(nums)
	for i:= range n {
		odds := make(map[int]int)
		evens := make(map[int]int)
		var t int = -1
		for j := i; j < n; j++ {
			if nums[j] % 2 == 1 {
				odds[nums[j]] = 1
			} else {
				evens[nums[j]] = 1
			}
			if len(odds) == len(evens) {
				t = j
			}
		}
		if ans < t - i + 1 {
			ans = t - i + 1
		}
	}
	return ans
}

func main() {
	fmt.Println("Hello world!")
}
