package main

import "fmt"

/**
 * problem A (1/4)
 * leetcode, weekly-contest-474
 * author: @shamir0xe
 * generated by contest-builder
 * https://github.com/shamir0xe/contest-builder
 **/
func findMissingElements(nums []int) []int {
	var mini int = 1e9
	var maxi int = -1
	res := make([]int, 0)
	all := make(map[int]int)
	for _, t := range nums {
		mini = min(t, mini)
		maxi = max(t, maxi)
		all[t] = 1
	}
	for i := range maxi - mini {
		candid := mini + i
		if _, ok := all[candid]; !ok {
			res = append(res, candid)
		}
	}
	return res
}

func main() {
	fmt.Println("Hello world!")
}
