package main

import (
	"bufio"
	"fmt"
	"os"
	"slices"
	"strings"
)

/**
 * problem A (1/6)
 * codeforces, codeforces-round-1057-div2
 * author: @shamir0xe
 * generated by contest-builder
 * https://github.com/shamir0xe/contest-builder
 **/

func main() {
	scanner := bufio.NewScanner(os.Stdin)
	var t int
	scanner.Scan()
	fmt.Sscanf(scanner.Text(), "%d", &t)
	for ; t > 0; t-- {
		var n int
		scanner.Scan()
		fmt.Sscanf(scanner.Text(), "%d", &n)
		var b []int = make([]int, n)

		scanner.Scan()
		for i, token := range strings.Fields(scanner.Text()) {
			b[i] = toInt(token)
		}

		slices.Sort(b)
		fmt.Printf("%d\n", len(slices.Compact(b)))
	}
}

func toInt(buf string) (n int) {
	for _, v := range buf {
		n = n*10 + int(v-'0')
	}
	return
}
