#include <bits/stdc++.h>
using namespace std;

/**
 * problem D (4/4)
 * leetcode, weekly-contest-367
 * author: @shamir0xe
 * generated by contest-builder
 * https://github.com/shamir0xe/contest-builder
 **/

typedef long long ll;
typedef pair<int, int> pii;
typedef vector<int> vi;
typedef vector<long long> vl;
typedef vector<vector<int>> vvi;
typedef vector<vector<ll>> vvl;
#define trace(x) cerr << #x << " : " << x << endl
#define _ << " " <<
#define sz(x) ((int)(x).size())
#define all(x) (x).begin(), (x).end()
#define X first
#define Y second

/**
 * printing tuples
 **/
template <size_t n, typename... T>
typename enable_if<(n >= sizeof...(T))>::type
__tuple_printer(ostream &os, const tuple<T...> &tup){};

template <size_t n, typename... T>
typename enable_if<(n < sizeof...(T))>::type
__tuple_printer(ostream &os, const tuple<T...> &tup) {
    if (n != 0)
        os << " ";
    os << get<n>(tup);
    __tuple_printer<n + 1>(os, tup);
};

template <typename... T>
std::ostream &operator<<(std::ostream &os, const std::tuple<T...> &tup) {
    os << "(";
    __tuple_printer<0>(os, tup);
    os << ")";
    return os;
}

/**
 * printing pairs
 **/
template <typename T, typename K>
ostream &operator<<(std::ostream &os, const std::pair<T, K> &p) {
    os << "(" << p.first << " " << p.second << ")";
    return os;
}

/**
 * printing vectors
 **/
template <class T>
std::ostream &operator<<(std::ostream &os, const std::vector<T> &v) {
    os << "[";
    bool first = true;
    for (auto ii = v.begin(); ii != v.end(); ++ii) {
        if (first)
            first = false;
        else
            os << " ";
        os << (*ii);
    }
    os << "]";
    return os;
}

/**
 * range functions
 **/
inline vi range(int idx, int n) {
    if (n <= idx)
        return vi();
    vi indices(n - idx);
    for (int i = idx; i < n; ++i)
        indices[i - idx] = i;
    return indices;
}

inline vi range(int n) { return range(0, n); }

// define variables here
#define MAX_M 15
int n;
const int mod = 12345;

// define functions here
int mul(int a, int b) { return (a * b) % mod; }

class Solution {
  public:
    vector<vector<int>> constructProductMatrix(vector<vector<int>> &grid) {
        int n = sz(grid);
        int m = sz(grid[0]);
        trace(n _ m);
        vi arr(n * m);
        for (int i: range(n)) {
            for (int j: range(m)) {
                trace(i _ j);
                arr[i * m + j] = grid[i][j];
            }
        }
        sort(all(arr));
        trace(arr);
        vi les(n * m, 1);
        vi ris(n * m, 1);
        for (int i: range(n * m)) {
            les[i] = arr[i] % mod;
            if (i - 1 >= 0)
                les[i] = mul(les[i], les[i - 1]);
        }
        for (int i = n * m - 1; i >= 0; i--) {
            ris[i] = arr[i] % mod;
            if (i + 1 < n * m)
                ris[i] = mul(ris[i], ris[i + 1]);
        }
        trace("after les ris");
        vvi res(n, vi(m));
        for (int i: range(n)) {
            for (int j: range(m)) {
                int idx = lower_bound(arr.begin(), arr.end(), grid[i][j]) -
                          arr.begin();
                trace(idx);
                int le = 1;
                if (idx - 1 >= 0)
                    le = les[idx - 1];
                int ri = 1;
                if (idx + 1 < n * m)
                    ri = ris[idx + 1];
                res[i][j] = mul(le, ri);
            }
        }
        return res;
    }
};

int read_input() {
    cin >> n;
    return 0;
}

auto solve() {
    /**
     * main logic goes here
     **/
    Solution solution = Solution();
    auto ans = solution.assert_yellow("Hello");
    return ans;
}

int second_main() {
    read_input();
    auto ans = solve();
    cout << ans << endl;
    return 0;
}

int main() {
    ios_base::sync_with_stdio(false);
    cin.tie(0);
    bool test_case = false;
    if (test_case) {
        int t;
        cin >> t;
        while (t--) {
            second_main();
        }
    } else {
        second_main();
    }
    return 0;
}
