package main

import "fmt"

/**
 * problem C (3/6)
 * codeforces, codeforces-round-1057-div2
 * author: @shamir0xe
 * generated by contest-builder
 * https://github.com/shamir0xe/contest-builder
 **/

func main() {
	fmt.Println("Hello world!")
}
