#include <bits/stdc++.h>

/**
 * problem E (5/9)
 * codeforces, good-bye-2025
 * author: @shamir0xe
 * generated by contest-builder
 * https://github.com/shamir0xe/contest-builder
 **/

typedef long long ll;
typedef std::pair<int, int> pii;
typedef std::vector<int> vi;
typedef std::vector<long long> vl;
typedef std::vector<std::vector<int>> vvi;
typedef std::vector<std::vector<ll>> vvl;
#define range(i, n) for (int i = 0; i < n; ++i)
#define rrange(i, n) for (int i = n - 1; i >= 0; --i)
#define fr(i, a, n) for (int i = a; i < n; ++i)
#define rfr(i, a, n) for (int i = n - 1; i >= a; --i)
#define trace(x) std::cerr << #x << " : " << x << std::endl
#define _ << " " <<
#define sz(x) ((int)(x).size())
#define all(x) (x).begin(), (x).end()
#define X first
#define Y second

/**
 * printing tuples
 **/
template <size_t n, typename... T>
typename std::enable_if<(n >= sizeof...(T))>::type
__tuple_printer(std::ostream &os, const std::tuple<T...> &tup) {};

template <size_t n, typename... T>
typename std::enable_if<(n < sizeof...(T))>::type
__tuple_printer(std::ostream &os, const std::tuple<T...> &tup) {
  if (n != 0) {
    os << " ";
  }
  os << std::get<n>(tup);
  __tuple_printer<n + 1>(os, tup);
};

template <typename... T>
std::ostream &operator<<(std::ostream &os, const std::tuple<T...> &tup) {
  os << "(";
  __tuple_printer<0>(os, tup);
  os << ")";
  return os;
}

/**
 * printing pairs
 **/
template <typename T, typename K>
std::ostream &operator<<(std::ostream &os, const std::pair<T, K> &p) {
  os << "(" << p.first << " " << p.second << ")";
  return os;
}

/**
 * printing vectors
 **/
template <class T>
std::ostream &operator<<(std::ostream &os, const std::vector<T> &v) {
  os << "[";
  bool first = true;
  for (auto ii = v.begin(); ii != v.end(); ++ii) {
    if (first) {
      first = false;
    } else {
      os << " ";
    }
    os << (*ii);
  }
  os << "]";
  return os;
}

template <typename T, typename K = std::function<void(void)>>
void smin(T &a, T b, const K callable = []() {}) {
  if (a > b) {
    a = b;
    callable();
  }
}

template <typename T, typename K = std::function<void(void)>>
void smax(T &a, T b, const K callable = []() {}) {
  if (a < b) {
    a = b;
    callable();
  }
}

/**
 * Reader class
 **/
class Reader {
public:
  template <typename T> inline static T primitive() {
    T temp;
    std::cin >> temp;
    return temp;
  }

  template <typename T> static std::vector<T> vector(int n) {
    std::vector<T> res(n);
    range(i, n) { res[i] = Reader::primitive<T>(); }
    return res;
  }

  template <typename T, size_t n> static std::array<T, n> array() {
    std::array<T, n> res;
    range(i, n) { res[i] = Reader::primitive<T>(); }
    return res;
  }

  static void sync() {
    std::ios_base::sync_with_stdio(false);
    std::cin.tie(nullptr);
  }
};

/**
 * define variables here
 **/
const int maxn = 1000 * 100 + 5;
int n;
std::map<pii, ll> memo;

/**
 * define functions here
 **/

ll query(int l, int r) {
  if (memo.count({l, r})) {
    return memo[{l, r}];
  }
  std::cout << "? " << l << " " << r << std::endl;
  std::cout.flush();
  ll res;
  std::cin >> res;
  memo[{l, r}] = res;
  return res;
}

int search(int i, int rr, ll pow2) {
  int l = i, r = rr;
  if (query(l, r) == pow2) {
    return r;
  }
  while (r - l > 1) {
    int mid = (l + r) / 2;
    ll res = query(i, mid);
    if (res >= pow2) {
      r = mid;
    } else {
      l = mid;
    }
  }
  ll res = query(i, l);
  if (res == pow2) {
    return l;
  }
  return r;
}

auto solve() {
  /**
   * main logic goes here
   **/
  std::cin >> n;
  memo.clear();

  if (n == 1) {
    return 1ll;
  }

  std::vector<pii> intervals;
  intervals.push_back({1, n});
  ll s = query(1, n);
  ll t = s;

  while (true) {
    t /= 2;
    std::vector<pii> nx_intervals;
    for (auto &[l, r] : intervals) {
      int m = search(l, r, t);
      if (m == l || m + 1 == r) {
        return t;
      }
      nx_intervals.push_back({l, m});
      nx_intervals.push_back({m + 1, r});
      // std::cout << "debug: " << l << " " << r << " " << m << std::endl;
    }
    std::map<int, pii> mp;
    for (auto &[l, r]: nx_intervals) {
      mp[r - l + 1] = {l, r};
    }
    intervals.clear();
    for (auto &[len, pr]: mp) {
      intervals.push_back(pr);
    }
  }
  return 1ll;
}

int second_main() {
  auto ans = solve();
  // range(i, n) { std::cout << ans[i] << " \n"[i == sz(ans) - 1]; }
  std::cout << "! " << ans << std::endl;
  std::cout.flush();
  return 0;
}

int main() {
  Reader::sync();
  bool test_case = true;
  if (test_case) {
    int t;
    std::cin >> t;
    while (t--) {
      second_main();
    }
  } else {
    second_main();
  }
  return 0;
}
