"""
LANG: PYTHON3
TASK: milk2
"""

## usaco, problemset
## author: @shamir0xe
## generated by contest-builder
## https://github.com/shamir0xe/contest-builder


def main():
    # generate input reader
    # generate events based on input
    fout = open ('milk2.out', 'w')
    fin = open ('milk2.in', 'r')

    x = lambda: fin.readline().strip()
    n = int(x())
    events = []
    for _ in range(n):
        start, stop = tuple(map(int, x().split(" ")))
        events.append((start, 0))
        events.append((stop, 1))
    events = sorted(events)

    # iterate over events and update the counter
    # ans:
    # calculate max non-null counter,
    # calculate max null counter,
    max_not_null, max_null = 0, 0
    counter = 0
    start_milking = -1
    stop_milking = -1
    for t, kind in events:
        if kind == 0:
            # starting point
            counter += 1
            if counter == 1:
                start_milking = t
                if stop_milking >= 0:
                    max_null = max(max_null, t - stop_milking)
        else:
            # stopping point
            counter -= 1
            if counter == 0:
                max_not_null = max(max_not_null, t - start_milking)
                stop_milking = t

    # generate output
    fout.write(f"{max_not_null} {max_null}\n")
    fout.close()


if __name__ == "__main__":
    main()
