import sys

## usaco, problemset
## author: @shamir0xe
## generated by contest-builder
## https://github.com/shamir0xe/contest-builder


def main():
    # generate input reader
    # generate events based on input
    in = lambda: sys.stdin.readline().strip()
    n = int(in())
    # iterate over events and update the counter
    # ans:
    # calculate max non-null counter,
    # calculate max null counter,
    
    # generate output
    print(f"{max_not_null} {max_null}")


if __name__ == "__main__":
    main()
