#include <bits/stdc++.h>
using namespace std;

/**
 * problem D (4/7)
 * codeforces, codeforces-round-903-div3
 * author: @shamir0xe
 * generated by contest-builder
 * https://github.com/shamir0xe/contest-builder
 **/

typedef long long ll;
typedef pair<int, int> pii;
typedef vector<int> vi;
typedef vector<long long> vl;
typedef vector<vector<int>> vvi;
typedef vector<vector<ll>> vvl;
#define trace(x) cerr << #x << " : " << x << endl
#define _ << " " <<
#define sz(x) ((int)(x).size())
#define all(x) (x).begin(), (x).end()
#define X first
#define Y second

/**
 * printing tuples
 **/
template <size_t n, typename... T>
typename enable_if<(n >= sizeof...(T))>::type
__tuple_printer(ostream &os, const tuple<T...> &tup){};

template <size_t n, typename... T>
typename enable_if<(n < sizeof...(T))>::type
__tuple_printer(ostream &os, const tuple<T...> &tup) {
    if (n != 0)
        os << " ";
    os << get<n>(tup);
    __tuple_printer<n + 1>(os, tup);
};

template <typename... T>
std::ostream &operator<<(std::ostream &os, const std::tuple<T...> &tup) {
    os << "(";
    __tuple_printer<0>(os, tup);
    os << ")";
    return os;
}

/**
 * printing pairs
 **/
template <typename T, typename K>
ostream &operator<<(std::ostream &os, const std::pair<T, K> &p) {
    os << "(" << p.first << " " << p.second << ")";
    return os;
}

/**
 * printing vectors
 **/
template <class T>
std::ostream &operator<<(std::ostream &os, const std::vector<T> &v) {
    os << "[";
    bool first = true;
    for (auto ii = v.begin(); ii != v.end(); ++ii) {
        if (first)
            first = false;
        else
            os << " ";
        os << (*ii);
    }
    os << "]";
    return os;
}

/**
 * range functions
 **/
inline vi range(int idx, int n) {
    if (n <= idx)
        return vi();
    vi indices(n - idx);
    for (int i = idx; i < n; ++i)
        indices[i - idx] = i;
    return indices;
}

inline vi range(int n) { return range(0, n); }

// define variables here
#define MAX_M 15
int n;
vi arr;
vi primes;
const int max_n = 1000 * 1000 + 5;

// define functions here

int read_input() {
    cin >> n;
    arr.resize(n);
    for (int i: range(n)) cin >> arr[i];
    return 0;
}

void sieve() {
    vector <char> is_prime;
    is_prime.assign(max_n, 1);
    for (int i = 2; i < max_n; ++i) {
        if (is_prime[i]) {
            primes.push_back(i);
            for (int j = i + i; j < max_n; j += i) is_prime[j] = 0;
        }
    }
}

map<int, int> decompose(int num) {
    map <int, int> mp;
    int idx = 0;
    while (true) {
        if (num < 1ll * primes[idx] * primes[idx]) break;
        while (num % primes[idx] == 0) {
            mp[primes[idx]] ++;
            num /= primes[idx];
        }
        idx++;
    }
    if (num != 1) mp[num]++;
    return mp;
}

void merge_sets(map<int, int> &mp, map<int, int> &t) {
    for (auto &[prime, cnt]: t) {
        mp[prime] += cnt;
    }
}

auto solve() {
    /**
     * main logic goes here
     **/
    map<int, int> all_composures;
    for (int number: arr) {
        auto temp = decompose(number);
        merge_sets(all_composures, temp);
    }
    // trace("TEST  ");
    for (auto &[prime, cnt]: all_composures) {
        // trace(prime _ cnt);
        if (cnt % n != 0) return "NO";
    }
    return "YES";
}

int second_main() {
    read_input();
    auto ans = solve();
    cout << ans << endl;
    return 0;
}

int main() {
    ios_base::sync_with_stdio(false);
    cin.tie(0);
    bool test_case = true;
    sieve();
    if (test_case) {
        int t;
        cin >> t;
        while (t--) {
            second_main();
        }
    } else {
        second_main();
    }
    return 0;
}
