package main

import "fmt"

/**
 * problem A (1/4)
 * leetcode, biweekly-contest-168
 * author: @shamir0xe
 * generated by contest-builder
 * https://github.com/shamir0xe/contest-builder
 **/

func lexSmallest(s string) string {
	n := len(s)
	res := "z"
	for i := range n - 1 {
		res += "z"
		i = i
	}

	fs := ""
	for i := range n {
		fs = string(s[i]) + fs
		candid := fs + s[i+1:]
		if candid < res {
			res = candid
		}
	}

	fs = ""
	for i := range n {
		j := n - i - 1
		fs = fs + string(s[j])
		candid := s[:j] + fs
		if candid < res {
			res = candid
		}
	}

	return res
}

func main() {
	fmt.Println("Hello world!")
}
