#include <bits/stdc++.h>

/**
 * problem C (3/8)
 * codeforces, codeforces-global-round-30-div1+div2
 * author: @shamir0xe
 * generated by contest-builder
 * https://github.com/shamir0xe/contest-builder
 **/

typedef long long ll;
typedef std::pair<int, int> pii;
typedef std::vector<int> vi;
typedef std::vector<long long> vl;
typedef std::vector<std::vector<int>> vvi;
typedef std::vector<std::vector<ll>> vvl;
#define range(i, n) for (int i = 0; i < n; ++i)
#define rrange(i, n) for (int i = n - 1; i >= 0; --i)
#define fr(i, a, n) for (int i = a; i < n; ++i)
#define rfr(i, a, n) for (int i = n - 1; i >= a; --i)
#define trace(x) std::cerr << #x << " : " << x << std::endl
#define _ << " " <<
#define sz(x) ((int)(x).size())
#define all(x) (x).begin(), (x).end()
#define X first
#define Y second

/**
 * printing tuples
 **/
template <size_t n, typename... T>
typename std::enable_if<(n >= sizeof...(T))>::type
__tuple_printer(std::ostream &os, const std::tuple<T...> &tup) {};

template <size_t n, typename... T>
typename std::enable_if<(n < sizeof...(T))>::type
__tuple_printer(std::ostream &os, const std::tuple<T...> &tup) {
    if (n != 0) {
        os << " ";
    }
    os << std::get<n>(tup);
    __tuple_printer<n + 1>(os, tup);
};

template <typename... T>
std::ostream &operator<<(std::ostream &os, const std::tuple<T...> &tup) {
    os << "(";
    __tuple_printer<0>(os, tup);
    os << ")";
    return os;
}

/**
 * printing pairs
 **/
template <typename T, typename K>
std::ostream &operator<<(std::ostream &os, const std::pair<T, K> &p) {
    os << "(" << p.first << " " << p.second << ")";
    return os;
}

/**
 * printing vectors
 **/
template <class T>
std::ostream &operator<<(std::ostream &os, const std::vector<T> &v) {
    os << "[";
    bool first = true;
    for (auto ii = v.begin(); ii != v.end(); ++ii) {
        if (first) {
            first = false;
        } else {
            os << " ";
        }
        os << (*ii);
    }
    os << "]";
    return os;
}

template <typename T, typename K = std::function<void(void)>>
void smin(T &a, T b, const K callable = []() {}) {
    if (a > b) {
        a = b;
        callable();
    }
}

template <typename T, typename K = std::function<void(void)>>
void smax(T &a, T b, const K callable = []() {}) {
    if (a < b) {
        a = b;
        callable();
    }
}

/**
 * Reader class
 **/
class Reader {
  public:
    template <typename T> inline static T primitive() {
        T temp;
        std::cin >> temp;
        return temp;
    }

    template <typename T> static std::vector<T> vector(int n) {
        std::vector<T> res(n);
        range(i, n) { res[i] = Reader::primitive<T>(); }
        return res;
    }

    template <typename T, size_t n> static std::array<T, n> array() {
        std::array<T, n> res;
        range(i, n) { res[i] = Reader::primitive<T>(); }
        return res;
    }

    static void sync() {
        std::ios_base::sync_with_stdio(false);
        std::cin.tie(nullptr);
    }
};

/**
 * define variables here
 **/
const int maxn = 1000 * 100 + 5;

/**
 * define functions here
 **/

auto solve(bool dbg) {
    /**
     * main logic goes here
     **/
    int n, m;
    std::cin >> n >> m;
    auto va = Reader::vector<int>(n);
    auto vb = Reader::vector<int>(m);
    auto vc = Reader::vector<int>(m);
    auto monsters = std::vector<pii>();

    std::multiset<int> mlefts;
    range(i, m) {
        if (vc[i] > 0) {
            monsters.push_back(pii{vb[i], -vc[i]});
        } else {
            mlefts.insert(vb[i]);
        }
    }
    m = sz(monsters);
    sort(all(va));
    sort(all(monsters));
    int ans = 0;
    std::multiset<int> swords[2];
    range(i, n) { swords[0].insert(va[i]); }

    if (m > 0) {
        int j = 0;
        while (sz(swords[0]) > 0 && j < m) {
            int sw = *swords[0].begin();
            swords[0].erase(swords[0].begin());
            if (sw < monsters[j].X) {
                swords[1].insert(sw);
            } else {
                swords[0].insert(std::max(sw, -monsters[j].Y));
                j++;
            }
        }
        ans = j;
    }
    while (sz(swords[0]) > 0) {
        swords[1].insert(*swords[0].begin());
        swords[0].erase(swords[0].begin());
    }
    while (sz(swords[1]) > 0 && sz(mlefts) > 0) {
        while (sz(swords[1]) > 0 && *swords[1].begin() < *mlefts.begin()) {
            swords[1].erase(swords[1].begin());
        }
        if (sz(swords[1]) == 0) {
            break;
        }
        ans++;
        swords[1].erase(swords[1].begin());
        mlefts.erase(mlefts.begin());
    }
    return ans;
}

vi results;
int second_main(bool dbg = false) {
    auto ans = solve(dbg);
    // range(i, n) { std::cout << ans[i] << " \n"[i == sz(ans) - 1]; }
    results.push_back(ans);
    return 0;
}

int main() {
    Reader::sync();
    bool test_case = true;
    if (test_case) {
        int t;
        std::cin >> t;
        for (int i = 1; i <= t; i++) {
            second_main(i == 1603);
        }
        for (int t: results) {
            std::cout << t << "\n";
        }
    } else {
        second_main();
    }
    return 0;
}
