package main

import "fmt"

/**
 * problem A (1/4)
 * leetcode, weekly-contest-472
 * author: @shamir0xe
 * generated by contest-builder
 * https://github.com/shamir0xe/contest-builder
 **/

func missingMultiple(nums []int, k int) int {
	var whole map[int]int = make(map[int]int)
	for _, t := range nums {
		if t%k == 0 {
			whole[t/k] = 1
		}
	}

	cnt := 1
	for true {
		if _, ok := whole[cnt]; !ok {
			break
		}
		cnt++
	}

	return cnt * k
}

func main() {
	fmt.Println("Hello world!")
}
