#include <bits/stdc++.h>
using namespace std;

/**
 * problem C (3/13)
 * codeforces,
 *compfest-15-preliminary-online-mirror-unrated-icpc-rules-teams-preferred
 * author: @shamir0xe
 * generated by contest-builder
 * https://github.com/shamir0xe/contest-builder
 **/

typedef long long ll;
typedef pair<int, int> pii;
typedef vector<int> vi;
typedef vector<long long> vl;
typedef vector<vector<int>> vvi;
typedef vector<vector<ll>> vvl;
#define trace(x) cerr << #x << " : " << x << endl
#define _ << " " <<
#define sz(x) ((int)(x).size())
#define all(x) (x).begin(), (x).end()
#define X first
#define Y second

/**
 * printing tuples
 **/
template <size_t n, typename... T>
typename enable_if<(n >= sizeof...(T))>::type
__tuple_printer(ostream &os, const tuple<T...> &tup){};

template <size_t n, typename... T>
typename enable_if<(n < sizeof...(T))>::type
__tuple_printer(ostream &os, const tuple<T...> &tup) {
    if (n != 0)
        os << " ";
    os << get<n>(tup);
    __tuple_printer<n + 1>(os, tup);
};

template <typename... T>
std::ostream &operator<<(std::ostream &os, const std::tuple<T...> &tup) {
    os << "(";
    __tuple_printer<0>(os, tup);
    os << ")";
    return os;
}

/**
 * printing pairs
 **/
template <typename T, typename K>
ostream &operator<<(std::ostream &os, const std::pair<T, K> &p) {
    os << "(" << p.first << " " << p.second << ")";
    return os;
}

/**
 * printing vectors
 **/
template <class T>
std::ostream &operator<<(std::ostream &os, const std::vector<T> &v) {
    os << "[";
    bool first = true;
    for (auto ii = v.begin(); ii != v.end(); ++ii) {
        if (first)
            first = false;
        else
            os << " ";
        os << (*ii);
    }
    os << "]";
    return os;
}

/**
 * range functions
 **/
inline vi range(int idx, int n) {
    if (n <= idx)
        return vi();
    vi indices(n - idx);
    for (int i = idx; i < n; ++i)
        indices[i - idx] = i;
    return indices;
}

inline vi range(int n) { return range(0, n); }

// define variables here
#define MAX_M 15
const int mod = 998244353;
int n;
vector<vector<pii>> adj;
vi t_ways, b_ways, t_ones;

// define functions here

int dfs(int u, vi &order) {
    t_ways[u] = 1;
    for (auto &[v, w]: adj[u]) {
        if (t_ways[v] == 0) {
            dfs(v, order);
        }
    }
    order.push_back(u);
    return 0;
}

int read_input() {
    cin >> n;
    adj.resize(n);
    for (int i: range(n)) {
        int t;
        cin >> t;
        while (t--) {
            int u, w;
            cin >> u >> w;
            adj[i].push_back({u - 1, w});
        }
    }
    return 0;
}

int add(int a, int b) { return (a + b) % mod; }

int mul(int a, int b) { return (1ll * a * b) % mod; }

auto solve() {
    /**
     * main logic goes here
     **/
    vi order;
    t_ways.assign(n, 0);
    dfs(0, order);
    reverse(all(order));
    t_ways.assign(n, 0);
    t_ones.assign(n, 0);
    t_ways[0] = 1;
    for (int u: order) {
        trace(u+1 _ t_ways[u] _ t_ones[u]);
        for (auto &[v, w]: adj[u]) {
            t_ways[v] = add(t_ways[v], t_ways[u]);
            t_ones[v] = add(t_ones[v], t_ones[u]);
            if (w == 1) {
                t_ones[v] = add(t_ones[v], t_ways[u]);
            }
        }
    }
    reverse(all(order));
    b_ways.assign(n, 0);
    for (int u: order) {
        int &ways = b_ways[u];
        for (auto &[v, w]: adj[u]) {
            ways = add(ways, b_ways[v]);
        }
        if (ways == 0) {
            ways = 1;
        }
    }
    int ans = 0;
    for (int u: range(n)) {
        for (auto &[v, w]: adj[u]) {
            if (w == 0) {
                ans = add(ans, mul(t_ones[u], b_ways[v]));
            }
        }
    }
    return ans;
}

int second_main() {
    read_input();
    auto ans = solve();
    cout << ans << endl;
    return 0;
}

int main() {
    ios_base::sync_with_stdio(false);
    cin.tie(0);
    bool test_case = false;
    if (test_case) {
        int t;
        cin >> t;
        while (t--) {
            second_main();
        }
    } else {
        second_main();
    }
    return 0;
}
