package main

import "fmt"

/**
 * problem C (3/4)
 * leetcode, weekly-contest-472
 * author: @shamir0xe
 * generated by contest-builder
 * https://github.com/shamir0xe/contest-builder
 **/

func lexGreaterPermutation(s string, target string) string {
	n := len(s)

	jump := func(index int) (string, error) {
		res := ""

		available := make(map[rune]int)
		for _, char := range s {
			available[char]++
		}

		get := func(t rune) rune {
			for i := int(rune(t) - 'a'); i < 26; i++ {
				char := rune('a' + i)
				if cnt, ok := available[char]; ok && cnt > 0 {
					return rune(char)
				}
			}
			return -1
		}

		getMin := func() rune {
			for i := range 26 {
				char := rune('a' + i)
				if cnt, ok := available[char]; ok && cnt > 0 {
					return rune(char)
				}
			}
			return -1
		}

		for i := range n {
			var cur rune = -1
			if i < index {
				cur = get(rune(target[i]))
				if cur > rune(target[i]) {
					index = i
				}
			} else if i == index {
				cur = get(rune(target[i]) + 1)
			} else {
				cur = getMin()
			}
			if cur == -1 {
				break
			}
			available[cur]--
			res += string(cur)
		}
		if len(res) == n {
			return res, nil
		}
		return "", fmt.Errorf("bad")
	}

	cur, err := jump(-1)

	fmt.Println(cur)

	if err == nil && cur > target {
		return cur
	}
	cur = ""
	for i := range n {
		t, err := jump(i)

		// fmt.Printf("%d: %s, %s\n", i, t, err)
		// fmt.Printf("%s>%s ? %b\n", t, target, t > target)

		if err == nil && t > target && (cur == "" || t < cur) {
			cur = t
		}
	}
	if cur != "" && cur > target {
		return cur
	}
	return ""
}

func main() {
	fmt.Println("Hello world!")
}
