#include <bits/stdc++.h>

/**
 * problem D (4/4)
 * leetcode, biweekly-contest-171
 * author: @shamir0xe
 * generated by contest-builder
 * https://github.com/shamir0xe/contest-builder
 **/

typedef long long ll;
typedef std::pair<int, int> pii;
typedef std::vector<int> vi;
typedef std::vector<long long> vl;
typedef std::vector<std::vector<int>> vvi;
typedef std::vector<std::vector<ll>> vvl;
#define range(i, n) for (int i = 0; i < n; ++i)
#define rrange(i, n) for (int i = n - 1; i >= 0; --i)
#define fr(i, a, n) for (int i = a; i < n; ++i)
#define rfr(i, a, n) for (int i = n - 1; i >= a; --i)
#define trace(x) std::cout << #x << " : " << x << std::endl
#define _ << " " <<
#define sz(x) ((int)(x).size())
#define all(x) (x).begin(), (x).end()
#define X first
#define Y second

/**
 * printing tuples
 **/
template <size_t n, typename... T>
typename std::enable_if<(n >= sizeof...(T))>::type
__tuple_printer(std::ostream &os, const std::tuple<T...> &tup) {};

template <size_t n, typename... T>
typename std::enable_if<(n < sizeof...(T))>::type
__tuple_printer(std::ostream &os, const std::tuple<T...> &tup) {
  if (n != 0) {
    os << " ";
  }
  os << std::get<n>(tup);
  __tuple_printer<n + 1>(os, tup);
};

template <typename... T>
std::ostream &operator<<(std::ostream &os, const std::tuple<T...> &tup) {
  os << "(";
  __tuple_printer<0>(os, tup);
  os << ")";
  return os;
}

/**
 * printing pairs
 **/
template <typename T, typename K>
std::ostream &operator<<(std::ostream &os, const std::pair<T, K> &p) {
  os << "(" << p.first << " " << p.second << ")";
  return os;
}

/**
 * printing vectors
 **/
template <class T>
std::ostream &operator<<(std::ostream &os, const std::vector<T> &v) {
  os << "[";
  bool first = true;
  for (auto ii = v.begin(); ii != v.end(); ++ii) {
    if (first) {
      first = false;
    } else {
      os << " ";
    }
    os << (*ii);
  }
  os << "]";
  return os;
}

template <typename T, typename K = std::function<void(void)>>
void smin(T &a, T b, const K callable = []() {}) {
  if (a > b) {
    a = b;
    callable();
  }
}

template <typename T, typename K = std::function<void(void)>>
void smax(T &a, T b, const K callable = []() {}) {
  if (a < b) {
    a = b;
    callable();
  }
}

/**
 * define variables here
 **/
const int maxn = 1000 * 100 + 5;

/**
 * define functions here
 **/
template <typename T> class FenwickTree {
private:
  int n;
  std::vector<T> tree;

public:
  FenwickTree(int size) : n(size), tree(size + 1, 0) {}

  void add(int idx, T delta) {
    assert(idx >= 0 && idx < n);

    for (int i = idx + 1; i <= n; i += i & -i) {
      tree[i] += delta;
    }
  }

  T query(int idx) const {
    if (idx >= n) {
      idx = n - 1;
    }
    if (idx < 0) {
      return 0;
    }

    T sum = 0;
    for (int i = idx + 1; i > 0; i -= i & -i) {
      sum += tree[i];
    }
    return sum;
  }

  // Returns sum in range [left, right] (inclusive)
  T query(int left, int right) const {
    if (left > right) {
      return 0;
    }
    return query(right) - query(left - 1);
  }
};

class Solution {
public:
  long long minInversionCount(std::vector<int> &nums, int k) {
    auto ft = FenwickTree<int>(maxn);
    std::map<int, int> mp;
    vi values;
    for (int t : nums) {
      values.push_back(t);
    }
    sort(all(values));
    values.erase(unique(all(values)), values.end());
    for (int i = 0; i < sz(values); ++i) {
      mp[values[i]] = i;
    }

    ll cur = 0;
    int i = 0;
    while (i < k) {
      cur += ft.query(mp[nums[i]] + 1, maxn - 1);
      ft.add(mp[nums[i]], 1);
      i++;
    }
    trace("init" _ cur);
    int n = sz(nums);
    ll ans = cur;
    while (i < n) {
      cur -= ft.query(mp[nums[i - k]] - 1);
      ft.add(mp[nums[i - k]], -1);
      ft.add(mp[nums[i]], 1);
      cur += ft.query(mp[nums[i]] + 1, maxn - 1);
      smin(ans, cur);
      trace(i+1 _ cur);
      i++;
    }
    return ans;
  }
};

std::vector<int> test_1() {
  std::string s{"barfoothefoobarman"};
  std::vector<std::string> words{"foo", "bar"};
  std::vector<int> res = Solution().findSubstring(s, words);
  return res;
}

std::vector<int> test_2() {
  std::string s{"wordgoodgoodgoodbestword"};
  std::vector<std::string> words{"word", "good", "best", "word"};
  std::vector<int> res = Solution().findSubstring(s, words);
  return res;
}

std::vector<int> test_3() {
  std::string s{"barfoofoobarthefoobarman"};
  std::vector<std::string> words{"bar", "foo", "the"};
  std::vector<int> res = Solution().findSubstring(s, words);
  return res;
}

int main() {
  auto res_1 = test_1();
  std::cout << "test #1: " << res_1 << std::endl;

  auto res_2 = test_2();
  std::cout << "test #2: " << res_2 << std::endl;

  auto res_3 = test_3();
  std::cout << "test #3: " << res_3 << std::endl;

  return 0;
}

//{:snippet}
//{:cutoff}
//{:tests}
//{:main}
