#include <bits/stdc++.h>
using namespace std;

/**
 * problem D (4/5)
 * codeforces, codeforces-round-904-div2
 * author: @shamir0xe
 * generated by contest-builder
 * https://github.com/shamir0xe/contest-builder
 **/

typedef long long ll;
typedef pair<int, int> pii;
typedef vector<int> vi;
typedef vector<long long> vl;
typedef vector<vector<int>> vvi;
typedef vector<vector<ll>> vvl;
#define trace(x) cerr << #x << " : " << x << endl
#define _ << " " <<
#define sz(x) ((int)(x).size())
#define all(x) (x).begin(), (x).end()
#define X first
#define Y second

/**
 * printing tuples
 **/
template <size_t n, typename... T>
typename enable_if<(n >= sizeof...(T))>::type
__tuple_printer(ostream &os, const tuple<T...> &tup){};

template <size_t n, typename... T>
typename enable_if<(n < sizeof...(T))>::type
__tuple_printer(ostream &os, const tuple<T...> &tup) {
    if (n != 0)
        os << " ";
    os << get<n>(tup);
    __tuple_printer<n + 1>(os, tup);
};

template <typename... T>
std::ostream &operator<<(std::ostream &os, const std::tuple<T...> &tup) {
    os << "(";
    __tuple_printer<0>(os, tup);
    os << ")";
    return os;
}

/**
 * printing pairs
 **/
template <typename T, typename K>
ostream &operator<<(std::ostream &os, const std::pair<T, K> &p) {
    os << "(" << p.first << " " << p.second << ")";
    return os;
}

/**
 * printing vectors
 **/
template <class T>
std::ostream &operator<<(std::ostream &os, const std::vector<T> &v) {
    os << "[";
    bool first = true;
    for (auto ii = v.begin(); ii != v.end(); ++ii) {
        if (first)
            first = false;
        else
            os << " ";
        os << (*ii);
    }
    os << "]";
    return os;
}

template <typename T, typename K = function<void(void)>>
void smin(
    T &a, T b, const K callable = []() {}) {
    if (a > b) {
        a = b;
        callable();
    }
}

template <typename T, typename K = function<void(void)>>
void smax(
    T &a, T b, const K callable = []() {}) {
    if (a < b) {
        a = b;
        callable();
    }
}

/**
 * range functions
 **/
inline vi range(int idx, int n) {
    if (n <= idx)
        return vi();
    vi indices(n - idx);
    for (int i = idx; i < n; ++i)
        indices[i - idx] = i;
    return indices;
}

inline vi range(int n) { return range(0, n); }

inline vi rrange(int idx, int n) {
    vi order = range(idx, n);
    reverse(all(order));
    return order;
}

inline vi rrange(int n) { return rrange(0, n); }

// define variables here
#define MAX_M 15
const int maxn = 1000 * 1000 + 10;
int n;
vvi primes(maxn);
vi arr;

// define functions here

void sieve() {
    vector<char> bl(maxn, 1);
    for (int i: range(2, maxn)) {
        if (bl[i]) {
            for (int j = i; j < maxn; j += i) {
                primes[j].push_back(i);
                bl[j] = 0;
            }
        }
    }
}

int read_input() {
    cin >> n;
    arr.resize(n);
    for (int i: range(n))
        cin >> arr[i];
    return 0;
}

int go(int a, int idx, int cur, vi &counts) {
    if (idx > sz(primes[a])) {
        trace(a _ cur);
        return counts[cur];
    }
    int ans = 0;
    ans += go(a, idx + 1, cur, counts);
    int res = primes[a][idx];
    while (a % res == 0) {
        ans += go(a, idx + 1, cur * res, counts);
        res *= primes[a][idx];
    }
    return ans;
}

auto solve() {
    /**
     * main logic goes here
     **/
    vector<ll> dp(n + 1, 0);
    vi counts(n + 1, 0);
    for (int i: range(n)) {
        counts[arr[i]]++;
    }
    for (int i: rrange(1, n + 1)) {
        ll &res = dp[i];
        int idx = i;
        while (idx <= n) {
            res += counts[idx];
            idx += i;
        }
        res = choose(2, res);
        idx = i + i;
        while (idx <= n) {
            res -= dp[idx];
            idx += i;
        }
    }
    vector<char> bl(n + 1, 0);
    for (int i: range(n)) {
        int idx = arr[i];
        while (idx <= n) {
            bl[idx] = 1;
            idx += arr[i;
        }
    }
    return dp[n - 1];
}

int second_main() {
    read_input();
    auto ans = solve();
    cout << ans << endl;
    return 0;
}

int main() {
    ios_base::sync_with_stdio(false);
    cin.tie(0);
    bool test_case = true;
    sieve();
    if (test_case) {
        int t;
        cin >> t;
        while (t--) {
            second_main();
        }
    } else {
        second_main();
    }
    return 0;
}
