#include <bits/stdc++.h>

/**
 * problem {:problem_alphabet} ({:problem_number}/{:total_problems})
 * {:provider}, {:contest_name}
 * author: @{:author}
 * generated by contest-builder
 * https://github.com/shamir0xe/contest-builder
 **/

typedef long long ll;
typedef std::pair<int, int> pii;
typedef std::vector<int> vi;
typedef std::vector<long long> vl;
typedef std::vector<std::vector<int>> vvi;
typedef std::vector<std::vector<ll>> vvl;
#define range(i, n) for (int i = 0; i < n; ++i)
#define rrange(i, n) for (int i = n - 1; i >= 0; --i)
#define fr(i, a, n) for (int i = a; i < n; ++i)
#define rfr(i, a, n) for (int i = n - 1; i >= a; --i)
#define trace(x) std::cerr << #x << " : " << x << std::endl
#define _ << " " <<
#define sz(x) ((int)(x).size())
#define all(x) (x).begin(), (x).end()
#define X first
#define Y second

/**
 * printing tuples
 **/
template <size_t n, typename... T>
typename std::enable_if<(n >= sizeof...(T))>::type
__tuple_printer(std::ostream &os, const std::tuple<T...> &tup) C;

template <size_t n, typename... T>
typename std::enable_if<(n < sizeof...(T))>::type
__tuple_printer(std::ostream &os, const std::tuple<T...> &tup) {
    if (n != 0) {
        os << " ";
    }
    os << std::get<n>(tup);
    __tuple_printer<n + 1>(os, tup);
};

template <typename... T>
std::ostream &operator<<(std::ostream &os, const std::tuple<T...> &tup) {
    os << "(";
    __tuple_printer<0>(os, tup);
    os << ")";
    return os;
}

/**
 * printing pairs
 **/
template <typename T, typename K>
std::ostream &operator<<(std::ostream &os, const std::pair<T, K> &p) {
    os << "(" << p.first << " " << p.second << ")";
    return os;
}

/**
 * printing vectors
 **/
template <class T>
std::ostream &operator<<(std::ostream &os, const std::vector<T> &v) {
    os << "[";
    bool first = true;
    for (auto ii = v.begin(); ii != v.end(); ++ii) {
        if (first) {
            first = false;
        } else {
            os << " ";
        }
        os << (*ii);
    }
    os << "]";
    return os;
}

template <typename T, typename K = std::function<void(void)>>
void smin(T &a, T b, const K callable = []() {}) {
    if (a > b) {
        a = b;
        callable();
    }
}

template <typename T, typename K = std::function<void(void)>>
void smax(T &a, T b, const K callable = []() {}) {
    if (a < b) {
        a = b;
        callable();
    }
}

/**
 * define variables here
 **/
const int maxn = 1000 * 100 + 5;

/**
 * define functions here
 **/

class Solution {
  public:
    std::vector<int> findSubstring(std::string s,
                                   std::vector<std::string> &words) {

        return vi3;
    }
};

std::vector<int> test_1() {
    std::string s{"barfoothefoobarman"};
    std::vector<std::string> words{"foo", "bar"};
    std::vector<int> res = Solution().findSubstring(s, words);
    return res;
}

std::vector<int> test_2() {
    std::string s{"wordgoodgoodgoodbestword"};
    std::vector<std::string> words{"word", "good", "best", "word"};
    std::vector<int> res = Solution().findSubstring(s, words);
    return res;
}

std::vector<int> test_3() {
    std::string s{"barfoofoobarthefoobarman"};
    std::vector<std::string> words{"bar", "foo", "the"};
    std::vector<int> res = Solution().findSubstring(s, words);
    return res;
}

int main() {
    auto res_1 = test_1();
    std::cout << "test #1: " << res_1 << std::endl;

    auto res_2 = test_2();
    std::cout << "test #2: " << res_2 << std::endl;

    auto res_3 = test_3();
    std::cout << "test #3: " << res_3 << std::endl;

    return 0;
}

//{:snippet}
//{:cutoff}
//{:tests}
//{:main}
