package main

import "fmt"

/**
 * problem D (4/4)
 * leetcode, weekly-contest-472
 * author: @shamir0xe
 * generated by contest-builder
 * https://github.com/shamir0xe/contest-builder
 **/

func main() {
	fmt.Println("Hello world!")
}
