package main

import "fmt"

/**
 * problem A (1/4)
 * leetcode, weekly-contest-471
 * author: @shamir0xe
 * generated by contest-builder
 * https://github.com/shamir0xe/contest-builder
 **/

func sumDivisibleByK(nums []int, k int) int {
	var counter []int = make([]int, 110)
	for _, value := range nums {
		counter[value]++
	}
	sum := 0
	for i, cnt := range counter {
		if cnt % k == 0 {
			sum += cnt * i
		}
	}
	return sum
}

func main() {
	fmt.Println("Hello world!")
}
