#include <bits/stdc++.h>

/**
 * problem D (4/6)
 * codeforces, educational-codeforces-round-160-rated-for-div2
 * author: @shamir0xe
 * generated by contest-builder
 * https://github.com/shamir0xe/contest-builder
 **/

typedef long long ll;
typedef std::pair<int, int> pii;
typedef std::vector<int> vi;
typedef std::vector<long long> vl;
typedef std::vector<std::vector<int>> vvi;
typedef std::vector<std::vector<ll>> vvl;
#define trace(x) std::cerr << #x << " : " << x << std::endl
#define _ << " " <<
#define sz(x) ((int)(x).size())
#define all(x) (x).begin(), (x).end()
#define X first
#define Y second

/**
 * printing tuples
 **/
template <size_t n, typename... T>
typename std::enable_if<(n >= sizeof...(T))>::type
__tuple_printer(std::ostream &os, const std::tuple<T...> &tup){};

template <size_t n, typename... T>
typename std::enable_if<(n < sizeof...(T))>::type
__tuple_printer(std::ostream &os, const std::tuple<T...> &tup) {
    if (n != 0) {
        os << " ";
    }
    os << std::get<n>(tup);
    __tuple_printer<n + 1>(os, tup);
};

template <typename... T>
std::ostream &operator<<(std::ostream &os, const std::tuple<T...> &tup) {
    os << "(";
    __tuple_printer<0>(os, tup);
    os << ")";
    return os;
}

/**
 * printing pairs
 **/
template <typename T, typename K>
std::ostream &operator<<(std::ostream &os, const std::pair<T, K> &p) {
    os << "(" << p.first << " " << p.second << ")";
    return os;
}

/**
 * printing vectors
 **/
template <class T>
std::ostream &operator<<(std::ostream &os, const std::vector<T> &v) {
    os << "[";
    bool first = true;
    for (auto ii = v.begin(); ii != v.end(); ++ii) {
        if (first) {
            first = false;
        } else {
            os << " ";
        }
        os << (*ii);
    }
    os << "]";
    return os;
}

template <typename T, typename K = std::function<void(void)>>
void smin(
    T &a, T b, const K callable = []() {}) {
    if (a > b) {
        a = b;
        callable();
    }
}

template <typename T, typename K = std::function<void(void)>>
void smax(
    T &a, T b, const K callable = []() {}) {
    if (a < b) {
        a = b;
        callable();
    }
}

/**
 * range functions
 **/
inline vi range(int idx, int n) {
    if (n <= idx) {
        return vi();
    }
    vi indices(n - idx);
    for (int i = idx; i < n; ++i) {
        indices[i - idx] = i;
    }
    return indices;
}

inline vi range(int n) { return range(0, n); }

inline vi rrange(int idx, int n) {
    vi order = range(idx, n);
    reverse(all(order));
    return order;
}

inline vi rrange(int n) { return rrange(0, n); }

class Reader {
  public:
    template <typename T> inline static T primitive() {
        T temp;
        std::cin >> temp;
        return temp;
    }

    template <typename T> static std::vector<T> vector(int n) {
        std::vector<T> res(n);
        for (int &i: range(n)) {
            res[i] = Reader::primitive<T>();
        }
        return res;
    }

    static void sync() {
        std::ios_base::sync_with_stdio(false);
        std::cin.tie(nullptr);
    }
};

/**
 * define variables here
 **/
const int maxn = 1000 * 100 + 5;
const int mod = 998244353;
int n;

/**
 * define functions here
 **/

int add(int a, int b) { return (a + b) % mod; }

auto solve() {
    /**
     * main logic goes here
     **/
    std::cin >> n;
    vi a = Reader::vector<int>(n);
    vi le(n, -1);
    for (int i: range(1, n)) {
        le[i] = i - 1;
        while (le[i] != -1 && a[le[i]] > a[i]) {
            le[i] = le[le[i]];
        }
    }
    int m = std::__lg(n) + 5;
    vvi rmq = vvi(n, vi(m));
    rmq[0][0] = 1;
    auto query = [&](int l, int r) -> int {
        int res = 0;
        int idx = r - 1;
        int length = r - l;
        while (length) {
            int high = std::__lg(length);
            res = add(res, rmq[idx][high]);
            idx -= 1 << high;
            length ^= 1 << high;
        }
        return res;
    };
    vi g(n);
    g[0] = 1;
    for (int i: range(1, n)) {
        int &res = rmq[i][0];
        res = query(le[i] + 1, i);
        if (le[i] != -1) {
            res = add(res, g[le[i]]);
        } else {
            res = add(res, 1);
        }
        g[i] = res;
        if (le[i] != -1) {
            g[i] = add(g[i], g[le[i]]);
        }
        for (int j: range(1, m)) {
            if (i - (1 << j) + 1 >= 0) {
                rmq[i][j] = add(rmq[i][j - 1], rmq[i - (1 << (j - 1))][j - 1]);
            }
        }
    }
    int idx = n - 1;
    int ans = 0;
    // for (int i: range(n)) {
    //     trace(i+1 _ rmq[i][0] _ le[i]+1);
    // }
    while (idx >= 0) {
        ans = add(ans, rmq[idx][0]);
        idx = le[idx];
    }
    // trace("");
    return ans;
}

int second_main() {
    auto ans = solve();
    // for (int i: range(sz(ans))) {
    //     std::cout << ans[i] << " \n"[i == sz(ans) - 1];
    // }
    std::cout << ans << std::endl;
    return 0;
}

int main() {
    Reader::sync();
    bool test_case = true;
    if (test_case) {
        int t;
        std::cin >> t;
        while (t--) {
            second_main();
        }
    } else {
        second_main();
    }
    return 0;
}
