#include <bits/stdc++.h>

/**
 * problem C (3/6)
 * codeforces, codeforces-round-1067-div2
 * author: @shamir0xe
 * generated by contest-builder
 * https://github.com/shamir0xe/contest-builder
 **/

typedef long long ll;
typedef std::pair<int, int> pii;
typedef std::vector<int> vi;
typedef std::vector<long long> vl;
typedef std::vector<std::vector<int>> vvi;
typedef std::vector<std::vector<ll>> vvl;
#define range(i, n) for (int i = 0; i < n; ++i)
#define rrange(i, n) for (int i = n - 1; i >= 0; --i)
#define fr(i, a, n) for (int i = a; i < n; ++i)
#define rfr(i, a, n) for (int i = n - 1; i >= a; --i)
#define trace(x) std::cerr << #x << " : " << x << std::endl
#define _ << " " <<
#define sz(x) ((int)(x).size())
#define all(x) (x).begin(), (x).end()
#define X first
#define Y second

/**
 * printing tuples
 **/
template <size_t n, typename... T>
typename std::enable_if<(n >= sizeof...(T))>::type
__tuple_printer(std::ostream &os, const std::tuple<T...> &tup) {};

template <size_t n, typename... T>
typename std::enable_if<(n < sizeof...(T))>::type
__tuple_printer(std::ostream &os, const std::tuple<T...> &tup) {
  if (n != 0) {
    os << " ";
  }
  os << std::get<n>(tup);
  __tuple_printer<n + 1>(os, tup);
};

template <typename... T>
std::ostream &operator<<(std::ostream &os, const std::tuple<T...> &tup) {
  os << "(";
  __tuple_printer<0>(os, tup);
  os << ")";
  return os;
}

/**
 * printing pairs
 **/
template <typename T, typename K>
std::ostream &operator<<(std::ostream &os, const std::pair<T, K> &p) {
  os << "(" << p.first << " " << p.second << ")";
  return os;
}

/**
 * printing vectors
 **/
template <class T>
std::ostream &operator<<(std::ostream &os, const std::vector<T> &v) {
  os << "[";
  bool first = true;
  for (auto ii = v.begin(); ii != v.end(); ++ii) {
    if (first) {
      first = false;
    } else {
      os << " ";
    }
    os << (*ii);
  }
  os << "]";
  return os;
}

template <typename T, typename K = std::function<void(void)>>
void smin(T &a, T b, const K callable = []() {}) {
  if (a > b) {
    a = b;
    callable();
  }
}

template <typename T, typename K = std::function<void(void)>>
void smax(T &a, T b, const K callable = []() {}) {
  if (a < b) {
    a = b;
    callable();
  }
}

/**
 * Reader class
 **/
class Reader {
public:
  template <typename T> inline static T primitive() {
    T temp;
    std::cin >> temp;
    return temp;
  }

  template <typename T> static std::vector<T> vector(int n) {
    std::vector<T> res(n);
    range(i, n) { res[i] = Reader::primitive<T>(); }
    return res;
  }

  template <typename T, size_t n> static std::array<T, n> array() {
    std::array<T, n> res;
    range(i, n) { res[i] = Reader::primitive<T>(); }
    return res;
  }

  static void sync() {
    std::ios_base::sync_with_stdio(false);
    std::cin.tie(nullptr);
  }
};

/**
 * define variables here
 **/
const int maxn = 1000 * 100 + 5;

/**
 * define functions here
 **/

auto solve() {
  /**
   * main logic goes here
   **/
  int n, k;
  std::cin >> n >> k;
  vi a = Reader::vector<int>(n);
  vi b = Reader::vector<int>(n);
  vl prefix = vl(n, 0);
  vl suffix = vl(n, 0);
  range(i, n) { prefix[i] = a[i] + (i > 0 ? prefix[i - 1] : 0); }
  rrange(i, n) { suffix[i] = a[i] + (i + 1 < n ? suffix[i + 1] : 0); }
  vl mp = vl(n, 0);
  rrange(i, n) {
    mp[i] = prefix[i];
    smax(mp[i], i + 1 < n ? mp[i + 1] : mp[i]);
  }
  vl ms = vl(n, 0);
  range(i, n) {
    ms[i] = suffix[i];
    smax(ms[i], i - 1 >= 0 ? ms[i - 1] : ms[i]);
  }
  ll best = -1e18;
  ll second_best = -1e18;
  range(i, n) {
    ll candid = mp[i] - prefix[i] + ms[i] - suffix[i] + a[i];
    smax(best, candid);
    candid += b[i];
    smax(second_best, candid);
  }
  if (k % 2 == 1) {
    return second_best;
  } else {
    return best;
  }
}

int second_main() {
  auto ans = solve();
  // range(i, n) { std::cout << ans[i] << " \n"[i == sz(ans) - 1]; }
  std::cout << ans << std::endl;
  return 0;
}

int main() {
  Reader::sync();
  bool test_case = true;
  if (test_case) {
    int t;
    std::cin >> t;
    while (t--) {
      second_main();
    }
  } else {
    second_main();
  }
  return 0;
}
