package main

import (
	"fmt"
	"sort"
)

/**
 * problem B (2/4)
 * leetcode, weekly-contest-474
 * author: @shamir0xe
 * generated by contest-builder
 * https://github.com/shamir0xe/contest-builder
 **/
func maxProduct(nums []int) int64 {
	abs := func(t int) int {
		if t < 0 {
			return -t
		}
		return t
	}
	sort.Slice(nums, func(i, j int) bool {
		return abs(nums[i]) < abs(nums[j])
	})
	sz := len(nums)
	for i := range sz {
		fmt.Printf("%d: %d\n", i, nums[i])
	}
	norm := func(t int) int {
		if t == 0 {
			return +1
		}
		return t / abs(t)
	}
	yekke := norm(nums[sz-1]) * norm(nums[sz-2])
	return int64(nums[sz-1]) * int64(nums[sz-2]) * int64(yekke*100*1000)
}

func main() {
	fmt.Println("Hello world!")
}
