package main

import (
	"slices"
	"fmt"
)

/**
 * problem D (4/4)
 * leetcode, weekly-contest-474
 * author: @shamir0xe
 * generated by contest-builder
 * https://github.com/shamir0xe/contest-builder
 **/

func lexPalindromicPermutation(s string, target string) string {
	res := ""
	sz := len(target)
	counts := make(map[rune]int)
	for _, ch := range s {
		if _, ok := counts[ch]; !ok {
			counts[ch] = 0
		}
		counts[ch]++
	}

	reverse := func(str string) string {
		byteStr := []byte(str)
		revBytes := make([]byte, len(byteStr))
		for i := range len(byteStr) {
			revBytes[i] = byteStr[len(byteStr)-1-i]
		}
		return string(revBytes)
	}

	build := func(counts map[rune]int, idx int, odd bool, midChar rune) string {
		res := ""
		for i := range idx {
			res += string(target[i])
			counts[rune(target[i])]--
			if counts[rune(target[i])] < 0 {
				return ""
			}
			if counts[rune(target[i])] == 0 {
				delete(counts, rune(target[i]))
			}
		}

		if idx >= 0 && idx < len(target) {
			var first rune = rune(target[idx]) + 1
			for first <= 'z' {
				if val, ok := counts[first]; ok && val > 0 {
					break
				}
				first++
			}
			if first <= 'z' {
				res += string(first)
				counts[first]--
				if counts[first] == 0 {
					delete(counts, first)
				}
			}
		}

		tt := ""
		for ch, count := range counts {
			if ch == midChar {
				count--
			}
			for i := range count {
				tt += string(ch)
				i = i
			}
		}
		ttBytes := []rune(tt)
		slices.Sort(ttBytes)
		tt = string(ttBytes)
		if midChar != -1 {
			if v, ok := counts[midChar]; ok && v > 0 {
				tt += string(midChar)
			}
		}

		res += tt

		var rev string
		if odd {
			rev = reverse(res[:len(res)-1])
		} else {
			rev = reverse(res)
		}
		res = res + rev

		return res
	}

	check := func(str string) bool {
		cnts := make(map[rune]int)
		for i := range len(str) {
			ch := rune(str[i])
			cnts[ch]++
			if cnts[ch] > counts[ch] {
				return false
			}
		}
		return true
	}

	for i := range (sz+1)/2 + 2 {
		// fill halfCounts
		halfCounts := make(map[rune]int)
		var midChar rune = -1
		for ch, cnt := range counts {
			if cnt%2 == 1 {
				midChar = ch
			}
			halfCounts[ch] = (cnt + 1) / 2
		}

		candid := build(halfCounts, i - 1, sz%2 == 1, midChar)
		fmt.Println(i)
		fmt.Println(candid)
		fmt.Println()

		if candid != "" && candid > target && len(candid) == sz && (res == "" || candid < res) {
			if check(candid) {
				res = candid
			}
		}
	}
	return res
}

func main() {
	fmt.Println("Hello world!")
}
