#include <bits/stdc++.h>
using namespace std;

/**
 * problem D (4/7)
 * codeforces, codeforces-round-902-div2-based-on-compfest-15-final-round
 * author: @shamir0xe
 * generated by contest-builder
 * https://github.com/shamir0xe/contest-builder
 **/

typedef long long ll;
typedef pair<int, int> pii;
typedef vector<int> vi;
typedef vector<long long> vl;
typedef vector<vector<int>> vvi;
typedef vector<vector<ll>> vvl;
#define trace(x) cerr << #x << " : " << x << endl
#define _ << " " <<
#define sz(x) ((int)(x).size())
#define all(x) (x).begin(), (x).end()
#define X first
#define Y second

/**
 * printing tuples
 **/
template <size_t n, typename... T>
typename enable_if<(n >= sizeof...(T))>::type
__tuple_printer(ostream &os, const tuple<T...> &tup){};

template <size_t n, typename... T>
typename enable_if<(n < sizeof...(T))>::type
__tuple_printer(ostream &os, const tuple<T...> &tup) {
    if (n != 0)
        os << " ";
    os << get<n>(tup);
    __tuple_printer<n + 1>(os, tup);
};

template <typename... T>
std::ostream &operator<<(std::ostream &os, const std::tuple<T...> &tup) {
    os << "(";
    __tuple_printer<0>(os, tup);
    os << ")";
    return os;
}

/**
 * printing pairs
 **/
template <typename T, typename K>
ostream &operator<<(std::ostream &os, const std::pair<T, K> &p) {
    os << "(" << p.first << " " << p.second << ")";
    return os;
}

/**
 * printing vectors
 **/
template <class T>
std::ostream &operator<<(std::ostream &os, const std::vector<T> &v) {
    os << "[";
    bool first = true;
    for (auto ii = v.begin(); ii != v.end(); ++ii) {
        if (first)
            first = false;
        else
            os << " ";
        os << (*ii);
    }
    os << "]";
    return os;
}

/**
 * range functions
 **/
inline vi range(int idx, int n) {
    if (n <= idx)
        return vi();
    vi indices(n - idx);
    for (int i = idx; i < n; ++i)
        indices[i - idx] = i;
    return indices;
}

inline vi range(int n) { return range(0, n); }

// define variables here
#define MAX_M 15
const int mod = 998244353;
int n;
vi arr;

// define functions here
void smax(int &a, int b) {
    if (a < b)
        a = b;
}

int mul(int a, int b) { return (1LL * a * b) % mod; }
int add(int a, int b) { return (a + b) % mod; }

int read_input() {
    cin >> n;
    arr.resize(n);
    for (int i: range(n)) {
        cin >> arr[i];
    }
    return 0;
}

auto solve() {
    /**
     * main logic goes here
     **/
    map<int, int> mp;
    for (int i: range(n)) {
        int cur = -1;
        for (int j = i; j < n; j += i + 1) {
            smax(cur, arr[j]);
        }
        mp[cur] += 1;
    }
    trace("HJERE");
    int ans = 0;
    int bef = 0;
    vi pow2{1};
    for (int i: range(1, n + 10)) {
        pow2.push_back(mul(pow2[i - 1], 2));
    }
    for (auto &[value, cnt]: mp) {
        ans = add(mul(add(pow2[cnt] - 1, mod), mul(pow2[bef], value)), ans);
        bef += cnt;
    }
    return ans;
}

int second_main() {
    read_input();
    auto ans = solve();
    cout << ans << endl;
    return 0;
}

int main() {
    ios_base::sync_with_stdio(false);
    cin.tie(0);
    bool test_case = false;
    if (test_case) {
        int t;
        cin >> t;
        while (t--) {
            second_main();
        }
    } else {
        second_main();
    }
    return 0;
}
