#include <bits/stdc++.h>

/**
 * problem C (3/5)
 * codeforces, codeforces-round-1063-div2
 * author: @shamir0xe
 * generated by contest-builder
 * https://github.com/shamir0xe/contest-builder
 **/

typedef long long ll;
typedef std::pair<int, int> pii;
typedef std::vector<int> vi;
typedef std::vector<long long> vl;
typedef std::vector<std::vector<int>> vvi;
typedef std::vector<std::vector<ll>> vvl;
#define range(i, n) for (int i = 0; i < n; ++i)
#define rrange(i, n) for (int i = n - 1; i >= 0; --i)
#define fr(i, a, n) for (int i = a; i < n; ++i)
#define rfr(i, a, n) for (int i = n - 1; i >= a; --i)
#define trace(x) std::cerr << #x << " : " << x << std::endl
#define _ << " " <<
#define sz(x) ((int)(x).size())
#define all(x) (x).begin(), (x).end()
#define X first
#define Y second

/**
 * printing tuples
 **/
template <size_t n, typename... T>
typename std::enable_if<(n >= sizeof...(T))>::type
__tuple_printer(std::ostream &os, const std::tuple<T...> &tup) {};

template <size_t n, typename... T>
typename std::enable_if<(n < sizeof...(T))>::type
__tuple_printer(std::ostream &os, const std::tuple<T...> &tup) {
    if (n != 0) {
        os << " ";
    }
    os << std::get<n>(tup);
    __tuple_printer<n + 1>(os, tup);
};

template <typename... T>
std::ostream &operator<<(std::ostream &os, const std::tuple<T...> &tup) {
    os << "(";
    __tuple_printer<0>(os, tup);
    os << ")";
    return os;
}

/**
 * printing pairs
 **/
template <typename T, typename K>
std::ostream &operator<<(std::ostream &os, const std::pair<T, K> &p) {
    os << "(" << p.first << " " << p.second << ")";
    return os;
}

/**
 * printing vectors
 **/
template <class T>
std::ostream &operator<<(std::ostream &os, const std::vector<T> &v) {
    os << "[";
    bool first = true;
    for (auto ii = v.begin(); ii != v.end(); ++ii) {
        if (first) {
            first = false;
        } else {
            os << " ";
        }
        os << (*ii);
    }
    os << "]";
    return os;
}

template <typename T, typename K = std::function<void(void)>>
void smin(T &a, T b, const K callable = []() {}) {
    if (a > b) {
        a = b;
        callable();
    }
}

template <typename T, typename K = std::function<void(void)>>
void smax(T &a, T b, const K callable = []() {}) {
    if (a < b) {
        a = b;
        callable();
    }
}

/**
 * Reader class
 **/
class Reader {
  public:
    template <typename T> inline static T primitive() {
        T temp;
        std::cin >> temp;
        return temp;
    }

    template <typename T> static std::vector<T> vector(int n) {
        std::vector<T> res(n);
        range(i, n) { res[i] = Reader::primitive<T>(); }
        return res;
    }

    template <typename T, size_t n> static std::array<T, n> array() {
        std::array<T, n> res;
        range(i, n) { res[i] = Reader::primitive<T>(); }
        return res;
    }

    static void sync() {
        std::ios_base::sync_with_stdio(false);
        std::cin.tie(nullptr);
    }
};

/**
 * define variables here
 **/
const int maxn = 1000 * 100 + 5;

/**
 * define functions here
 **/

pii apply(pii a, pii b) {
  return {std::min(a.X, b.X), std::max(a.Y, b.Y)};
}

auto solve() {
    /**
     * main logic goes here
     **/
    int n;
    std::cin >> n;
    vi a = vi(2, vi(n));
    range(i, 2) {
      range(j, n) {
        std::cin >> a[i][j];
      }
    }
    std::vector<pii> bots;
    std::vector<pii> tops[2] = {{}, {}};
    rrange(j, n) {
      bots[j] = {a[1][j], a[1][j]};
      if (j + 1 < n) {
        bots[j] = apply(bots[j], bots[j + 1]);
      }
    }

    rrange(j, n) {
      tops[0][j] = {a[0][j], a[0][j]};
      tops[1][j] = {a[0][j], a[0][j]};
      if (j + 1 < n) {
        tops[0][j] = apply(tops[0][j], tops[0][j + 1]);
      }
      tops[1][j] = apply(tops[1][j], bots[j]);
    }

    ll ans = 1ll * tops[0][0].X * (2 * n - tops[0][0].Y + 1);
    ans += 1ll * tops[1][0].X * (2 * n - tops[1][0].Y + 1);
    pii common = tops[0][0];
    common = apply(common, tops[1][0]);
    ans -= 1ll * common.X * (2 * n - common.Y + 1);

    return ans;
}

int second_main() {
    auto ans = solve();
    // range(i, n) { std::cout << ans[i] << " \n"[i == sz(ans) - 1]; }
    std::cout << ans << std::endl;
    return 0;
}

int main() {
    Reader::sync();
    bool test_case = true;
    if (test_case) {
        int t;
        std::cin >> t;
        while (t--) {
            second_main();
        }
    } else {
        second_main();
    }
    return 0;
}
