package main

import "fmt"

/**
 * problem A (1/4)
 * leetcode, biweekly-contest-167
 * author: @shamir0xe
 * generated by contest-builder
 * https://github.com/shamir0xe/contest-builder
 **/

func scoreBalance(s string) bool {
	n := len(s)
	calc := func(str string) int {
		res := 0
		for _, char := range str {
			res += int(char - 'a') + 1
		}
		return res
	}
	for i := range n - 1 {
		if calc(s[:i+1]) == calc(s[i+1:]) {
			return true
		}
	}
	return false
}

func main() {
	fmt.Println("Hello world!")
}
