package main

import "fmt"

/**
 * problem {} ({}/{})
 * {}, {}
 * author: @shamir0xe
 * generated by contest-builder
 * https://github.com/shamir0xe/contest-builder
 **/

func main() {
	fmt.Println("Hello world!")
}
